# Generated by Django 4.1.1 on 2022-09-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='concert',
            new_name='concerts',
        ),
    ]
