# Generated by Django 4.1.1 on 2022-09-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_group_singer', to='users.groupsinger'),
        ),
        migrations.AddField(
            model_name='concert',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_place', to='users.place'),
        ),
    ]
